config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  resources :products, path: "/"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    accept_language = request.env["HTTP_ACCEPT_LANGUAGE"].to_s
    accept_language.scan(/^[a-z]{2}/).first || I18n.default_locale
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to categories_url, notice: t(".created")
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
      if category.update(category_params)
        redirect_to categories_url, notice: t(".updated")
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    category.destroy!
      redirect_to categories_path, status: :see_other, notice: t(".destroyed")
  end

  private
    def category
      @category = Category.find(params.expect(:id))
    end

    def category_params
      params.expect(category: [ :name ])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.order(name: :asc).load_async
    @products = Product.with_attached_photo.order(created_at: :desc).load_async
    if params[:category_id].present?
      @products = @products.where(category_id: params[:category_id])
    end

    if params[:min_price].present?
      @products = @products.where("price >= ?", params[:min_price])
    end
    if  params[:max_price].present?
      @products = @products.where("price <= ?", params[:max_price])
    end
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end
  def destroy
    product.destroy
    redirect_to products_path, notice: t(".destroyed")
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t(".updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :photo, :category_id)
  end

  def product
    @product ||= Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
    <%= category.name %>
    <%= link_to t('.edit'), edit_category_path(category) %>
    <%= link_to t('.delete'), category_path(category), data: { 
        turbo_method: :delete,
        turbo_confirm: t('common.confirm') 
        } %>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
<% @category.errors.full_messages.each do |error| %>
        <div>
        <%= error %>
        </div>
    <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<%= render partial: 'category', collection: @categories %>
<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Vendelo - Compra y vende productos de segunda mano" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: "category" do %>
    <%= category.name %>
<% end %>

app/views/products/_price.html.erb
<%= product.price %>

app/views/products/_product.html.erb
    <%= link_to product_path(product.id), class:'product', 'data-turbo-frame': '_top'  do %>
            <h2><%= product.title %> </h2>
           <div>
               <%= image_tag product.photo, class: "img-fluid", width: 100 if product.photo.attached?%>
            </div>
            <h3><%= product.price %> $</h3>
    <% end %>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'shared/product_form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'categories' do %>
<h1><%= t('.title') %></h1>

<%= form_with url: products_path, method: :get do |form| %>
    <%= form.number_field :min_price, placeholder: t('.min_price'),
    onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
     <%= form.number_field :max_price, placeholder: t('.max_price'),
     onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
<% end %>

<%= link_to t('common.all'), products_path %>

<%= render partial: 'category', collection: @categories %>
<%= render partial: 'product', collection: @products %>

<% end %>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'shared/product_form' %>

app/views/products/show.html.erb
 <div>
               <%= image_tag @product.photo, class: "img-fluid", width: 200 if @product.photo.attached?%>
            </div>

<h1 class="title">
    <%= @product.title%>
</h1>
<p class="description">
 <%= @product.description %>
</p>
<p class="price">
 <%= @product.price %> $
</p>


<%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: t('common.confirm') } %>
<%= link_to "Editar", edit_product_path %>
<%= link_to "Back", products_path %> 

app/views/shared/_flash.html.erb
<%= notice %>

  <%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1>Véndelo</h1>
<% end %>

    <%= link_to t('common.add_product'), new_product_path %>
    <%= link_to t('common.categories'), categories_path %>

app/views/shared/_product_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <div>
        <%= error %>
        </div>
    <% end %>
    <div>
        <%= form.label :title %>
    <%= form.text_field :title %>
    </div>

        <div>
 <%= form.label :description %>
    <%= form.text_area :description %>
    </div>

        <div>
        <%= form.label :price %>
    <%= form.number_field :price %>
    </div>

    <div>
        <%= form.label :category_id %>
        <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
    </div>

    <div>
        <%= form.label :photo %>
    <%= form.file_field :photo %>
    </div>

    <%= form.submit%>

<% end %>